apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: starlark-fn
  annotations:
    config.kubernetes.io/local-config: "true"
source: |
  print("[INFO] Running Starlark function via ctx")
  new_parameter =  None
  for resource in ctx.resource_list["items"]:
    if resource["kind"] == "ConfigMap" and resource["metadata"]["name"] == "subpackage-parameters":
      new_parameter = resource["data"]["parent"]
      print("[INFO] This key-value pair is added by parent rendering")

  for resource in ctx.resource_list["items"]:
    if resource["kind"] == "ConfigMap" and resource["metadata"]["name"] == "my-config":
      resource["data"]["parent"] = new_parameter
      print("[INFO] Generate my-config file from parent-parameter")
